"use client";

import Link from "next/link";
import { DeleteButton } from "@/components/delete-button";
import { useParams } from "next/navigation";
import { useCallback, useEffect, useState } from "react";
import { Icon } from "@/components/icons";
import {
  ErrorNotice,
  Modal,
  PageHeader,
  Spinner,
  StatusBadge,
} from "@/components/ui";
import { useAuth } from "@/context/auth-context";
import { api, errorMessage } from "@/lib/api";
import {
  findingLabels,
  formatDate,
  statusLabels,
} from "@/lib/format";
import { sourceHref } from "@/lib/source";
import type {
  AnalysisRun,
  Citation,
  Decision,
  DocumentRecord,
  Report,
} from "@/lib/types";

export default function RunPage() {
  const { id } = useParams<{ id: string }>();
  const { user } = useAuth();
  const [run, setRun] = useState<AnalysisRun | null>(null);
  const [error, setError] = useState("");
  const [source, setSource] = useState<Citation | null>(null);
  const [documents, setDocuments] = useState<DocumentRecord[]>([]);
  const [retrying, setRetrying] = useState(false);
  const [sourceError, setSourceError] = useState("");
  const load = useCallback(async () => {
    try {
      setRun(await api<AnalysisRun>(`/api/runs/${id}`));
      setError("");
    } catch (reason) {
      setError(errorMessage(reason));
    }
  }, [id]);
  useEffect(() => {
    void load();
  }, [load]);
  useEffect(() => {
    if (!run?.case_id) return;
    let active = true;
    setDocuments([]);
    setSourceError("");
    Promise.allSettled([api<DocumentRecord[]>("/api/documents?kind=policy"), api<DocumentRecord[]>(`/api/documents?kind=evidence&case_id=${encodeURIComponent(run.case_id)}`)])
      .then((results) => {
        if (!active) return;
        setDocuments(results.flatMap((result) => result.status === "fulfilled" ? result.value : []));
        if (results.some((result) => result.status === "rejected")) setSourceError("Some source filenames could not be loaded. You can still open each citation.");
      })
      .catch(() => { if (active) setSourceError("Source filenames could not be loaded. You can still open each citation."); });
    return () => { active = false; };
  }, [run?.case_id]);
  useEffect(() => {
    if (!run || !(run.status === "queued" || run.status === "running")) return;
    const timer = setInterval(() => void load(), 1800);
    return () => clearInterval(timer);
  }, [load, run]);
  async function retry() {
    setRetrying(true);
    try { await api(`/api/runs/${id}/retry`, {method: "POST"}); await load(); }
    catch (reason) { setError(errorMessage(reason)); }
    finally { setRetrying(false); }
  }
  const decision = run?.decision ?? null;
  if (!run && !error) return <Spinner label="Loading analysis…" />;
  if (!run) return <ErrorNotice message={error} retry={load} />;
  const canWrite = user?.role === "reviewer" || (user?.role === "analyst" && !run.case_is_decided);
  const processing = run.status === "queued" || run.status === "running";
  return (
    <>
      {sourceError && <ErrorNotice message={sourceError} />}
      <PageHeader
        eyebrow="Analysis"
        title="Assessment report"
        description={`Run ${run.id}`}
        actions={
          <>
            <DeleteButton allowed={canWrite && (user?.role === "reviewer" || !decision)} endpoint={`/api/runs/${id}`} label="Delete report" redirect={`/cases/${run.case_id}`}
              confirmation="Permanently delete this report, its decision and saved analysis progress? Source documents remain. This cannot be undone." />
            <Link className="button button-quiet" href={`/cases/${run.case_id}`}>
              Back to case
            </Link>
          </>
        }
      />
      {error && <ErrorNotice message={error} />}
      <RunProgress run={run} />
      {processing && (
        <section className="card">
          <Spinner
            label={
              run.status === "queued"
                ? "The analysis is waiting for an available worker…"
                : "Retrieving evidence and evaluating requirements…"
            }
          />
        </section>
      )}
      {run.status === "failed" && (
        <div style={{marginBottom: 18}}>
          <ErrorNotice message={run.error || run.progress?.error || "The analysis failed."} />
          {canWrite && !run.retry_blocked_reason && <button className="button" disabled={retrying} onClick={retry}>{retrying ? "Resuming…" : "Resume unfinished requirements"}</button>}
          {run.retry_blocked_reason && <p className="subtle">{run.retry_blocked_reason}</p>}
          <p className="subtle">Completed requirement assessments are preserved.</p>
        </div>
      )}{" "}
      {run.report && !processing && run.status !== "failed" && (
        <>
          {run.report.recorded_example && (
            <div className="notice" style={{ marginBottom: 18 }}>
              <strong>Recorded Gemini example</strong>
              <p>This report was generated by {run.report.recorded_example.model_name} on {formatDate(run.report.recorded_example.captured_at)} using synthetic documents.
                Loading this example makes no model calls. Human review decisions are recorded separately.</p>
            </div>
          )}
          <div className="stat-grid">
            <article className="card stat">
              <span className="stat-label">Risk</span>
              <span className="stat-value">
                <StatusBadge value={run.report.risk}>
                  {run.report.risk}
                </StatusBadge>
              </span>
            </article>
            <article className="card stat">
              <span className="stat-label">Evidence completeness</span>
              <span className="stat-value">{run.report.completeness}%</span>
              <div className="progress-track">
                <div
                  className="progress-value"
                  style={{ width: `${run.report.completeness}%` }}
                />
              </div>
            </article>
            <article className="card stat">
              <span className="stat-label">Human decision</span>
              <span className="stat-value" style={{ fontSize: 18 }}>
                {decision ? (
                  <StatusBadge value={decision.decision}>
                    {statusLabels[decision.decision]}
                  </StatusBadge>
                ) : (
                  <StatusBadge value="awaiting_review">
                    Awaiting decision
                  </StatusBadge>
                )}
              </span>
            </article>
          </div>
          <section className="card report-summary">
            <h2>Summary</h2>
            <p>{run.report.summary}</p>
          </section>
          <div className="detail-grid" style={{ marginTop: 18 }}>
            <div className="stack">
              <section>
                <h2 style={{ font: "600 24px Georgia,serif" }}>
                  Findings ({run.report.findings.length})
                </h2>
                <div className="stack">
                  {run.report.findings.map((finding) => (
                    <article
                      className="card finding"
                      key={finding.requirement_id}
                    >
                      <div className="finding-header">
                        <div>
                          <StatusBadge value={finding.status}>
                            {findingLabels[finding.status]}
                          </StatusBadge>
                          <h3>{finding.title}</h3>
                        </div>
                        <StatusBadge value={finding.severity}>
                          {finding.severity}
                        </StatusBadge>
                      </div>
                      <div className="finding-body">
                        <p>{finding.explanation}</p>
                        {(finding.missing_information?.length ?? 0) > 0 && (
                          <div className="notice notice-info">
                            <p>
                              <strong>Missing information:</strong>{" "}
                              {finding.missing_information?.join(" ")}
                            </p>
                          </div>
                        )}
                        <div className="requirement-grid">
                          <div><h4>Policy requirement</h4>
                            <p>{finding.requirement_description ?? finding.requirement_source?.quote ?? "See the approved policy version for this requirement."}</p>
                            {finding.requirement_source && <button className="evidence-quote" onClick={() => setSource(finding.requirement_source!)}>
                              <span>{documents.find((document) => document.id === finding.requirement_source?.document_id)?.filename ?? "Policy source"} · View quoted passage</span>
                            </button>}
                          </div>
                          <div><h4>Counterparty evidence</h4>
                          {finding.evidence.length === 0 && <p className="subtle">No supporting evidence was found.</p>}
                        {finding.evidence.map((evidence) => (
                          <button
                            className="evidence-quote"
                            key={`${evidence.chunk_id}-${evidence.quote}`}
                            onClick={() => setSource(evidence)}
                          >
                            <q>{evidence.quote}</q>
                            <span>
                              <Icon
                                name="source"
                                style={{ width: 14, verticalAlign: "middle" }}
                              />{" "}
                              {evidence.evidence_type === "independent"
                                ? "independent evidence"
                                : "declaration"}{" "}
                              · {documents.find((document) => document.id === evidence.document_id)?.filename ?? "Source document"}
                              {" · "}View quoted passage
                            </span>
                          </button>
                        ))}
                          </div>
                        </div>
                      </div>
                    </article>
                  ))}
                </div>
              </section>
              <ReportLists
                questions={run.report.questions}
                discrepancies={run.report.discrepancies}
              />
            </div>
            <aside className="stack">
              <DecisionPanel
                key={run.id}
                run={run}
                decision={decision}
                canDecide={
                  user?.role === "reviewer"
                }
                saved={load}
              />
            </aside>
          </div>
        </>
      )}
      {source && (
        <SourceModal citation={source} close={() => setSource(null)} />
      )}
    </>
  );
}

function RunProgress({ run }: { run: AnalysisRun }) {
  const lastAnalysisEvent = run.events?.filter(({ event }) =>
    event.startsWith("run.") || event.startsWith("analysis."),
  ).at(-1);
  const steps = [
    { key: "queued", label: "Created" },
    { key: "running", label: "Analysis" },
    { key: "awaiting_review", label: "Review" },
    { key: "completed", label: "Decision" },
  ];
  const index =
    run.status === "failed"
      ? 1
      : steps.findIndex((entry) => entry.key === run.status);
  return (
    <section className="card" style={{ marginBottom: 18 }}>
      <div className="card-body">
        <div
          style={{
            display: "flex",
            alignItems: "center",
            justifyContent: "space-between",
            gap: 10,
          }}
        >
          {steps.map((step, i) => (
            <div
              key={step.key}
              style={{ flex: 1, textAlign: "center", position: "relative" }}
            >
              <span
                className={`badge ${i <= index ? "badge-success" : "badge-neutral"}`}
              >
                {i < index || (step.key === "completed" && run.decision) ? "✓ " : ""}
                {step.label}
              </span>
              {i < steps.length - 1 && (
                <span
                  aria-hidden="true"
                  style={{
                    height: 1,
                    background: i < index ? "var(--pine)" : "var(--line)",
                    position: "absolute",
                    top: "50%",
                    left: "65%",
                    right: "-35%",
                    zIndex: -1,
                  }}
                />
              )}
            </div>
          ))}
        </div>
        {run.progress && <div aria-live="polite" style={{marginTop: 18}}>
          <p>{run.progress.completed} of {run.progress.total} requirements assessed</p>
          <progress aria-label="Requirement assessment progress" value={run.progress.completed} max={Math.max(run.progress.total, 1)} style={{width: "100%"}} />
          {run.progress.current_requirement_id && <p className="subtle">Current requirement: {run.progress.current_requirement_id}</p>}
        </div>}
        {lastAnalysisEvent && (
          <p
            className="subtle"
            style={{ textAlign: "center", margin: "14px 0 0" }}
          >
            {runEventLabel(lastAnalysisEvent.event)}
          </p>
        )}
      </div>
    </section>
  );
}

function runEventLabel(event: string): string {
  const labels: Record<string, string> = {
    "analysis.queued": "Analysis queued",
    "run.started": "Analysis started",
    "run.awaiting_review": "Report awaiting review",
    "analysis.decision": "Decision recorded",
    "run.completed": "Analysis completed",
    "run.retry_scheduled": "Analysis retry scheduled",
    "run.failed": "Analysis failed",
  };
  if (labels[event]) return labels[event];
  if (event.startsWith("run.") || event.startsWith("analysis.")) {
    return "Analysis status updated";
  }
  return "Analysis status updated";
}

function ReportLists({
  questions,
  discrepancies,
}: {
  questions: string[];
  discrepancies: Report["discrepancies"];
}) {
  if (!questions.length && !discrepancies.length) return null;
  return (
    <div className="split-list">
      {questions.length > 0 && (
        <section className="card">
          <div className="card-header">
            <h2>Follow-up questions</h2>
          </div>
          <div className="card-body">
            <ol className="plain-list">
              {questions.map((question, index) => (
                <li key={index}>{question}</li>
              ))}
            </ol>
          </div>
        </section>
      )}
      {discrepancies.length > 0 && (
        <section className="card">
          <div className="card-header">
            <h2>Discrepancies</h2>
          </div>
          <div className="card-body">
            <ul className="plain-list">
              {discrepancies.map((item, index) => (
                <li key={index}>{item.description}</li>
              ))}
            </ul>
          </div>
        </section>
      )}
    </div>
  );
}

function DecisionPanel({
  run,
  decision,
  canDecide,
  saved,
}: {
  run: AnalysisRun;
  decision: Decision | null;
  canDecide: boolean;
  saved: () => Promise<void>;
}) {
  const [value, setValue] = useState<Decision["decision"]>("needs_information");
  // Initialize once: refreshing run metadata must not replace work in progress.
  const [questions, setQuestions] = useState(
    run.information_request_draft?.text ?? run.report?.questions.join("\n") ?? "",
  );
  const [rationale, setRationale] = useState("");
  const [pending, setPending] = useState("");
  const [error, setError] = useState("");
  const [notice, setNotice] = useState("");
  const [editing, setEditing] = useState(false);
  const isRequest = !canDecide || value === "needs_information";
  const savedMessage = run.information_request_draft;
  const readOnlyRequest = isRequest && !!savedMessage && !editing;
  const text = isRequest ? (readOnlyRequest ? savedMessage!.text : questions) : rationale;
  async function submit(event: React.FormEvent) {
    event.preventDefault();
    await save(canDecide ? "decision" : "draft");
  }
  async function save(action: "draft" | "decision") {
    setPending(action);
    setError("");
    setNotice("");
    try {
      await api(`/api/runs/${run.id}/${action === "draft" ? "information-request-draft" : "decision"}`, {
        method: action === "draft" ? "PUT" : "POST",
        body: JSON.stringify(action === "draft" ? { text: questions } : { decision: value, rationale: text }),
      });
      await saved();
      if (action === "draft") {
        setEditing(false);
        setNotice("Draft saved for reviewer review.");
      }
    } catch (reason) {
      setError(errorMessage(reason));
    } finally {
      setPending("");
    }
  }
  return (
    <section className="card">
      <div className="card-header"><h2>Decision</h2></div>
      <div className="card-body">
        {decision ? (
          <>
            <StatusBadge value={decision.decision}>{statusLabels[decision.decision]}</StatusBadge>
            <p style={{ whiteSpace: "pre-wrap" }}>{decision.rationale}</p>
            <span className="subtle">{formatDate(decision.created_at)}</span>
          </>
        ) : run.status !== "awaiting_review" ? (
          <p className="subtle">A decision can be recorded after the report is ready.</p>
        ) : run.case_is_decided && !canDecide ? (
          <p className="subtle">This case already has a final decision.</p>
        ) : (
          <form onSubmit={submit}>
            {error && <ErrorNotice message={error} />}
            {notice && <p role="status">{notice}</p>}
            {canDecide ? <div className="decision-options">
              {([
                ["accepted", "Accept"],
                ["rejected", "Reject"],
                ["needs_information", "Request information"],
              ] as const).map(([key, label]) => (
                <button type="button" key={key} disabled={!!pending}
                  className={`decision-option ${value === key ? "selected" : ""}`}
                  onClick={() => setValue(key)}>{label}</button>
              ))}
            </div> : <p className="subtle">Prepare an information request for the reviewer. Only a reviewer can record the decision.</p>}
            {isRequest && <p className="subtle">Questions are saved in this report. Nothing is sent externally.</p>}
            {isRequest && run.information_request_draft && <p className="subtle">
              Draft saved by {run.information_request_draft.actor_email ?? run.information_request_draft.actor_id} · {formatDate(run.information_request_draft.updated_at)}
            </p>}
            {readOnlyRequest ? <div>
              <p style={{ whiteSpace: "pre-wrap" }}>{savedMessage!.text}</p>
              {!canDecide && <p className="subtle">Submitted for reviewer review.</p>}
            </div> : <label className="field">
              <span>{isRequest ? "Information request" : "Decision rationale"}</span>
              <textarea className="textarea" required minLength={5} maxLength={10000} disabled={!!pending}
                value={text} onChange={(event) => {
                  if (isRequest) setQuestions(event.target.value); else setRationale(event.target.value);
                  setNotice("");
                }}
                placeholder={isRequest ? "Describe the information the counterparty should provide." : "Explain which findings informed the decision."} />
            </label>}
            {(canDecide || !readOnlyRequest) && <div className="form-actions"
              style={{ gap: 12, marginTop: 16, flexWrap: "wrap" }}>
              {canDecide && readOnlyRequest && <button type="button" className="button button-secondary"
                disabled={!!pending} onClick={() => { setQuestions(savedMessage!.text); setEditing(true); setNotice(""); }}>
                Edit
              </button>}
            {canDecide && isRequest && !readOnlyRequest && <button type="button" className="button button-secondary"
              disabled={!!pending || questions.trim().length < 5} onClick={() => void save("draft")}>
              {pending === "draft" ? "Saving…" : "Save draft"}
            </button>}
            {(canDecide || !readOnlyRequest) && <button className="button" disabled={!!pending || text.trim().length < 5}>
              {pending ? "Saving…" : canDecide ? "Save decision" : "Save draft"}
            </button>}
            </div>}
          </form>
        )}
      </div>
    </section>
  );
}

function SourceModal({
  citation,
  close,
}: {
  citation: Citation;
  close: () => void;
}) {
  const [document, setDocument] = useState<DocumentRecord | null>(null);
  const [error, setError] = useState("");
  useEffect(() => {
    api<DocumentRecord>(`/api/documents/${citation.document_id}`)
      .then(setDocument)
      .catch((reason) => setError(errorMessage(reason)));
  }, [citation.document_id]);
  return (
    <Modal title="Evidence source" close={close}>
      <div className="modal-content">
        {error && <ErrorNotice message={error} />}{" "}
        {!document && !error && <Spinner label="Loading document…" />}
        {document && (
          <>
            <p>
              <strong>{document.filename}</strong>
              <br />
              <span className="subtle">
                Quoted passage
              </span>
            </p>
            <blockquote className="source-document">
              <mark className="source-highlight">{citation.quote}</mark>
            </blockquote>
            <Link
              className="arrow-link"
              href={sourceHref(citation)}
            >
              Open full document <Icon name="arrow" />
            </Link>
          </>
        )}
      </div>
    </Modal>
  );
}
